version: "3"

services:
    first:
        image: node:latest
        working_dir: /app
        build: .
        ports:
            - 5002:5002
        volumes:
            - .:/app/
        command: bash -c "cd assignment1 && npm install && npm run dev -- --host --port 5002"

    second:
        image: node:latest
        working_dir: /app
        build:  .
        ports:
            - 5003:5002
        volumes:
            - .:/app/
        command: bash -c "cd assignment2 && npm install && npm run dev -- --host --port 5002"
